---
- name: create IntelliJ IDEA user options directory
  become: yes
  file:
    dest: "/home/{{ item.username }}/{{ intellij_user_dir }}/config/options"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 'ug=rwx,o=rx'
  with_items: "{{ users }}"

- name: configure project
  become: yes
  template:
    src: project.default.xml.j2
    dest: "/home/{{ item.username }}/{{ intellij_user_dir }}/config/options/project.default.xml"
    force: no
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 'ug=rw,o=r'
  with_items: "{{ users }}"
