---
# Needed by custom Ansible modules
- name: install Python XML support (Python 2)
  become: yes
  package:
    name: python-lxml
    state: present
  when: "intellij_python_major_version == '2' and ansible_os_family != 'Darwin'"

- name: install Python XML support (Python 3)
  become: yes
  package:
    name: "python3-lxml"
    state: present
  when: "intellij_python_major_version == '3' and ansible_os_family != 'Darwin'"

- name: install Python XML support (Python 3)
  become: yes
  command: "pip3 install lxml"
  when: "ansible_os_family == 'Darwin'"

- import_tasks: configure-license.yml

- import_tasks: configure-disabled-plugins.yml

- import_tasks: configure-jdk-table.yml

- import_tasks: configure-project-defaults.yml

- import_tasks: install-code-styles.yml

- import_tasks: configure-code-style.yml

- import_tasks: install-inspection-profiles.yml

- import_tasks: configure-inspection-profiles.yml

- import_tasks: install-plugins.yml
