---
- name: include OS family specific vars
  with_first_found:
    - '../vars/os-families/{{ ansible_os_family }}-{{ ansible_machine }}.yml'
    - '../vars/os-families/{{ ansible_os_family }}.yml'
    - ../vars/os-families/default.yml
  include_vars: '{{ item }}'

- name: assert edition vars
  assert:
    that:
      - "intellij_edition in ('community', 'ultimate')"

- name: load edition vars
  include_vars: '../vars/editions/{{ intellij_edition }}.yml'

- name: install dependencies
  become: yes
  when: ansible_os_family != 'Darwin'
  package:
    name: '{{ intellij_dependencies }}'
    state: present

- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ intellij_download_dir }}'

- name: stat install dir
  stat:
    path: '{{ intellij_product_info_dir }}'
  register: stat_install_dir

- name: Get intellij product json
  when: (stat_install_dir.stat.exists is defined and stat_install_dir.stat.exists)
  set_fact:
    current_installed_version: |
      {{ lookup('file',intellij_product_info_dir + '/product-info.json')
       | from_json | json_query('version') }}

- name: Set should download new versionn
  set_fact:
    should_download_and_install: |
      {{ ((not stat_install_dir.stat.exists is defined or not stat_install_dir.stat.exists)
       or (not current_installed_version is defined or current_installed_version != intellij_version)) | bool }}

- name: display stat_install_dir
  debug: msg="{{ stat_install_dir }}"

- name: display should_download_and_install
  debug: msg="{{ should_download_and_install }}"

- name: get sha from jetbrains
  set_fact:
    intellij_sha256sum: "{{ lookup('url', intellij_mirror + '/' + intellij_redis_filename + '.sha256', split_lines=False) }}"

- name: download IntelliJ IDEA
  get_url:
    url: '{{ intellij_mirror }}/{{ intellij_redis_filename }}'
    dest: '{{ intellij_download_dir }}/{{ intellij_redis_filename }}'
    checksum: 'sha256:{{ intellij_sha256sum[:64] }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    timeout: '{{ intellij_idea_download_timeout_seconds }}'
    mode: 'u=rw,go=r'
  when: should_download_and_install

- name: create IntelliJ IDEA installation directory
  when: ansible_os_family != 'Darwin' and should_download_and_install
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '{{ intellij_install_dir }}'

- name: install IntelliJ IDEA
  become: yes
  when: ansible_os_family != 'Darwin' and should_download_and_install
  unarchive:
    src: '{{ intellij_download_dir }}/{{ intellij_redis_filename }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    dest: '{{ intellij_install_dir }}'
    owner: root
    group: root
    mode: 'o-w'
    creates: '{{ intellij_install_dir }}/bin'

- name: create bin link
  when: ansible_os_family != 'Darwin' and should_download_and_install
  become: yes
  file:
    src: '{{ intellij_install_dir }}/bin/idea.sh'
    dest: /usr/local/bin/idea
    state: link
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: install IntelliJ IDEA desktop file
  become: yes
  when: ansible_os_family != 'Darwin' and should_download_and_install
  template:
    src: jetbrains-idea.desktop.j2
    dest: '/usr/share/applications/{{ intellij_desktop_filename }}'
    owner: root
    group: root
    mode: 'u=rw,go=r'

## OSX
- name: Create tmp dir as dmg mounting point;
  file:
    path: ./tmp/
    mode: 'u=rwx,go=rx'
    state: directory
  when: should_download_and_install and ansible_os_family == 'Darwin'

- name: Mount dmg to tmp dir
  command: hdiutil attach '{{ intellij_download_dir }}/{{ intellij_redis_filename }}' -nobrowse -mountpoint ./tmp/idea
  when: should_download_and_install and ansible_os_family == 'Darwin'

- name: Copy app to Applications.
  copy:
    src: "./tmp/idea/{{ intellij_app_name }}.app"
    remote_src: yes
    dest: "/Applications/{{ intellij_app_name }}.app"
    mode: preserve
  when: should_download_and_install and ansible_os_family == 'Darwin'

- name: Unmount dmg
  command: hdiutil detach ./tmp/idea/
  when: should_download_and_install and ansible_os_family == 'Darwin'

- name: Remove tmp mounting dir
  file:
    path: ./tmp/
    state: absent
  when: should_download_and_install and ansible_os_family == 'Darwin'

- name: install Ansible facts.d directory (Linux)
  become: yes
  when: ansible_os_family != 'Darwin'
  file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: install IntelliJ facts (Linux)
  become: yes
  when: ansible_os_family != 'Darwin'
  template:
    src: facts.j2
    dest: /etc/ansible/facts.d/intellij.fact
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: install Ansible facts.d directory (OSX)
  become: yes
  when: ansible_os_family == 'Darwin'
  file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: root
    group: wheel
    mode: 'u=rwx,go=rx'

- name: install IntelliJ facts (OSX)
  become: yes
  when: ansible_os_family == 'Darwin'
  template:
    src: facts.j2
    dest: /etc/ansible/facts.d/intellij.fact
    owner: root
    group: wheel
    mode: 'u=rw,go=r'

- name: re-read facts
  setup: filter=ansible_local
